// Generated by Selenium IDE
const { Builder, By, Key, until, Browser } = require("selenium-webdriver");
const assert = require("assert");
const { suite } = require("selenium-webdriver/testing");

suite(
  function (env) {
    describe("Make a test with an error login", function () {
      this.timeout(30000);
      let driver;
      before(async function () {
        driver = await new Builder().forBrowser("chrome").build();
      });
      after(async () => await driver.quit());
      it("Test with an error login", async function () {
        await driver.get("https://www.facebook.com/");
        await driver.manage().window().setRect({ width: 968, height: 1020 });
        await driver.findElement(By.id("email")).sendKeys("test1@gmail.com");
        await driver.findElement(By.id("pass")).sendKeys("123456789");
        await driver.findElement(By.name("login")).click();
      });
    });
  },
  { Browser: [Browser.CHROME] }
);
